#include "OpenGLShaderManager.hpp"

#define VS_BASIC_SOURCE_FILE "Shaders/basic_vs.glsl"
#define PS_BASIC_SOURCE_FILE "Shaders/basic_ps.glsl"
#define VS_SHADOWMAP_SOURCE_FILE "Shaders/shadowmap_vs.glsl"
#define PS_SHADOWMAP_SOURCE_FILE "Shaders/shadowmap_ps.glsl"
#define VS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/shadowmap_omni_vs.glsl"
#define PS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/shadowmap_omni_ps.glsl"
#define GS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/shadowmap_omni_gs.glsl"
#define DEBUG_VS_SHADER_SOURCE_FILE "Shaders/debug_vs.glsl"
#define DEBUG_PS_SHADER_SOURCE_FILE "Shaders/debug_ps.glsl"
#define VS_PASSTHROUGH_SOURCE_FILE "Shaders/passthrough_vs.glsl"
#define PS_TEXTURE_SOURCE_FILE "Shaders/texture_ps.glsl"
#define PS_DEPTH_TEXTURE_ARRAY_SOURCE_FILE "Shaders/depthtexturearray_ps.glsl"
#define VS_PASSTHROUGH_CUBEMAP_SOURCE_FILE "Shaders/passthrough_cube_vs.glsl"
#define PS_CUBEMAP_ARRAY_SOURCE_FILE "Shaders/cubemaparray_ps.glsl"
#define PS_DEPTH_CUBEMAP_ARRAY_SOURCE_FILE "Shaders/depthcubemaparray_ps.glsl"
#define PS_SIMPLE_CUBEMAP_SOURCE_FILE "Shaders/cubemap_ps.glsl"
#define VS_SKYBOX_SOURCE_FILE "Shaders/skybox_vs.glsl"
#define PS_SKYBOX_SOURCE_FILE "Shaders/skybox_ps.glsl"
#define PS_PBR_SOURCE_FILE "Shaders/pbr_ps.glsl"
#define CS_PBR_BRDF_SOURCE_FILE "Shaders/integrateBRDF.comp"
#define PS_PBR_BRDF_SOURCE_FILE "Shaders/integrateBRDF_ps.glsl"

#include "OpenGLShaderManagerCommonBase.cpp"