#include "OpenGLESShaderManager.hpp"

#define VS_SHADER_SOURCE_FILE "Shaders/OpenGLES/basic_vs.glsl"
#define PS_SHADER_SOURCE_FILE "Shaders/OpenGLES/basic_ps.glsl"
#define VS_SHADOWMAP_SOURCE_FILE "Shaders/OpenGLES/shadowmap_vs.glsl"
#define PS_SHADOWMAP_SOURCE_FILE "Shaders/OpenGLES/shadowmap_ps.glsl"
#define VS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/OpenGLES/shadowmap_omni_vs.glsl"
#define PS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/OpenGLES/shadowmap_omni_ps.glsl"
#define GS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/OpenGLES/shadowmap_omni_gs.glsl"
#define DEBUG_VS_SHADER_SOURCE_FILE "Shaders/OpenGLES/debug_vs.glsl"
#define DEBUG_PS_SHADER_SOURCE_FILE "Shaders/OpenGLES/debug_ps.glsl"
#define VS_PASSTHROUGH_SOURCE_FILE "Shaders/OpenGLES/passthrough_vs.glsl"
#define PS_SIMPLE_TEXTURE_SOURCE_FILE "Shaders/OpenGLES/depthtexture_ps.glsl"
#define VS_PASSTHROUGH_CUBEMAP_SOURCE_FILE "Shaders/OpenGLES/passthrough_cube_vs.glsl"
#define PS_SIMPLE_DEPTH_CUBEMAP_SOURCE_FILE "Shaders/OpenGLES/depthcubemap_ps.glsl"
#define PS_SIMPLE_CUBEMAP_SOURCE_FILE "Shaders/OpenGLES/cubemap_ps.glsl"
#define VS_SKYBOX_SOURCE_FILE "Shaders/OpenGLES/skybox_vs.glsl"
#define PS_SKYBOX_SOURCE_FILE "Shaders/OpenGLES/skybox_ps.glsl"

#include "OpenGLShaderManagerCommonBase.cpp"