#include "OpenGLShaderManager.hpp"

#define VS_BASIC_SOURCE_FILE "Shaders/OpenGL/basic.vert.glsl"
#define PS_BASIC_SOURCE_FILE "Shaders/OpenGL/basic.frag.glsl"
#define VS_SHADOWMAP_SOURCE_FILE "Shaders/OpenGL/shadowmap.vert.glsl"
#define PS_SHADOWMAP_SOURCE_FILE "Shaders/OpenGL/shadowmap.frag.glsl"
#define VS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/OpenGL/shadowmap_omni.vert.glsl"
#define PS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/OpenGL/shadowmap_omni.frag.glsl"
#define GS_OMNI_SHADOWMAP_SOURCE_FILE "Shaders/OpenGL/shadowmap_omni.geom.glsl"
#define DEBUG_VS_SHADER_SOURCE_FILE "Shaders/OpenGL/debug.vert.glsl"
#define DEBUG_PS_SHADER_SOURCE_FILE "Shaders/OpenGL/debug.frag.glsl"
#define VS_PASSTHROUGH_SOURCE_FILE "Shaders/OpenGL/passthrough.vert.glsl"
#define PS_TEXTURE_SOURCE_FILE "Shaders/OpenGL/texture.frag.glsl"
#define PS_DEPTH_TEXTURE_ARRAY_SOURCE_FILE "Shaders/OpenGL/depthtexturearray.frag.glsl"
#define VS_PASSTHROUGH_CUBEMAP_SOURCE_FILE "Shaders/OpenGL/passthrough_cube.vert.glsl"
#define PS_CUBEMAP_ARRAY_SOURCE_FILE "Shaders/OpenGL/cubemaparray.frag.glsl"
#define PS_DEPTH_CUBEMAP_ARRAY_SOURCE_FILE "Shaders/OpenGL/depthcubemaparray.frag.glsl"
#define PS_SIMPLE_CUBEMAP_SOURCE_FILE "Shaders/OpenGL/cubemap.frag.glsl"
#define VS_SKYBOX_SOURCE_FILE "Shaders/OpenGL/skybox.vert.glsl"
#define PS_SKYBOX_SOURCE_FILE "Shaders/OpenGL/skybox.frag.glsl"
#define PS_PBR_SOURCE_FILE "Shaders/OpenGL/pbr.frag.glsl"
#define CS_PBR_BRDF_SOURCE_FILE "Shaders/OpenGL/integrateBRDF.comp.glsl"
#define PS_PBR_BRDF_SOURCE_FILE "Shaders/OpenGL/integrateBRDF.frag.glsl"
#define VS_TERRAIN_SOURCE_FILE "Shaders/OpenGL/terrain.vert.glsl"
#define PS_TERRAIN_SOURCE_FILE "Shaders/OpenGL/terrain.frag.glsl"
#define TESC_TERRAIN_SOURCE_FILE "Shaders/OpenGL/terrain.tesc.glsl"
#define TESE_TERRAIN_SOURCE_FILE "Shaders/OpenGL/terrain.tese.glsl"

#include "OpenGLShaderManagerCommonBase.cpp"